### ISSUE TITLE
Release a 2024.1 compatible version

### ISSUE THREAD

**Issue by CyrilleB79** [josephsl/soundSplitter#7]
Unless an unexpected issue is found, SoundSplit will be a core feature in NVDA 2024.2. As of today, it will only be supported if WASAPI is enabled (default value).

For users of NVDA 2024.1 or for users of future 2024.2 with WASAPI disabled, it would be nice to have a compatible version.

Note that I have overridden compatibility and I am using the add-on with 2024.1 for many weeks now.

Thanks.

**Comment by XLTechie** [comment]
My apologies, this one fell under my radar; I thought I had done them all.
Will get this later today.

**Comment by CyrilleB79** [comment]
Thanks!

**Comment by XLTechie** [comment]
Support is available in 24.0.500 (dev channel), and will shortly be available in 24.0.0. (stable channel).

Apologies for this taking longer than I expected.
